spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/biznopay
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration