apiVersion: v1
kind: Secret
metadata:
  name: biznopay-secrets
  namespace: biznopay
type: Opaque
stringData:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
  SPRING_DATASOURCE_USERNAME: postgres.iybbdxrrwedqqazxkxyo
  SPRING_DATASOURCE_PASSWORD: EfcWefEKQltSjxr1
  SERVER_URL: http://138.128.240.137:30000